### PR TITLE
ATO-NONE: Add acceptance tests

### PR DESCRIPTION
**Pull request by hannah-leong**
## What?

Add acceptance tests to existing user journey
- Different scopes (only openid)
- Different claims (without address and with driving permit)
- HTTP POST method

Update readme to:
- Update AWS account name
- Mention installing a driver as a prerequisite
- Mention changing email addresses for running locally

## Why?

Test more cases and update the readme

### CODE REVIEW

**Comment by CraigRyder** [comment]
Creation of the new user also needs to be added to the reset-test-data.sh script so as to reset the data prior to a test run. You'll probably be bale to work out what needs to be done from the existing users that are in that script but give me a shout if not.

**Review by CraigRyder — CHANGES_REQUESTED** [review]
Creation of the new user also needs to be added to the reset-test-data.sh script so as to reset the data prior to a test run. You'll probably be bale to work out what needs to be done from the existing users that are in that script but give me a shout if not.

**Comment by hannah-leong** [comment]
Ah thanks - I made the change locally but forgot to commit it!

**Comment by whi-tw** [comment]
@hannah-leong is this still necessary / relevant? if so, can you please fix the conflicts. if not, can you please close it?

**Pull request closed without merging**
